// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: DICE RCE

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_SALUT = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SALUT = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SALUT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SALUT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SALUT, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SALUT, "SALUT\n");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_SALUT = NULL;

}
